config/routes.rb
Rails.application.routes.draw do

  resources :coders, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :languages, only: [:index, :new, :create, :destroy]

  get '/', to: 'root#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coder.rb
class Coder < ApplicationRecord
  has_many :skillsets
  has_many :languages, through: :skillsets

  validates_presence_of :first_name, :last_name, :about, :looking_for, :img_url
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :skillsets
  has_many :coders, through: :skillsets

  validates_presence_of :name
end

app/models/skillset.rb
class Skillset < ApplicationRecord
  belongs_to :coder
  belongs_to :language
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController

  def index
    @coders = Coder.all
  end

  def show
    @coder = Coder.find(params[:id])
    @skillsets = @coder.skillsets.all
  end

  def new
    @coder = Coder.new
  end

  def create
    @coder = Coder.new(coder_params)
    if @coder.save
      redirect_to coder_path(@coder)
    else
      render :new
    end
  end

  def edit
    @coder = Coder.find(params[:id])
  end

  def update
    @coder = Coder.find(params[:id])
    @coder.update(coder_params)
    if @coder.save
      flash[:success] = "#{@coder.first_name} updated!"
      redirect_to coder_path(@coder)
    else
      render :edit
    end
  end

  def destroy
    coder = Coder.find(params[:id])
    coder.destroy
    redirect_to coders_path
    flash[:success] = "Coder has been deleted from the database!"
  end

  private

  def coder_params
    params.require(:coder).permit(:first_name, :last_name, :about, :looking_for, :img_url)
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @languages = Language.all
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)
    if @language.save
      redirect_to languages_path
    else
      render :new
    end
  end

  def destroy
    language = Language.find(params[:id])
    language.destroy
    redirect_to languages_path
    flash[:success] = "Language has been deleted from the database!"
  end

  private

  def language_params
    params.require(:language).permit(:name)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coders/_form.html.erb
<%= form_for(@coder) do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.label :about %><br>
  <%= f.text_area :about %><br>

  <%= f.label :looking_for %><br>
  <%= f.text_area :looking_for %><br>

  <%= f.label :image_path %><br>
  <%= f.text_field :img_url %><br>

  <%= f.submit %>
<% end %>

app/views/coders/edit.html.erb
<h1>Edit Coder</h1>
<%= render partial: "form" %>

<%= link_to "Delete Coder", coder_path(@coder), method: :delete %>

app/views/coders/index.html.erb
<h3>ALL CODERS</h3>
<%= link_to "Add New Coder to Database", new_coder_path %>
<div class="row">
<% @coders.each do |coder| %>
  <div class="col-md-2 index-card">
    <div class="index_card">
    <img src="<%= coder.img_url %>" alt="Coder Image" class="code_index_img"><br>
    <h5><a href="/coders/<%= coder.id %>"><%= coder.first_name %> <br> <%= coder.last_name %></a></h5>
  </div>
  </div>
<% end %>
</div>

app/views/coders/new.html.erb
Create a New Coder

<%= form_for(@coder) do |f| %>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br>

  <%= f.label :about %><br>
  <%= f.text_area :about %><br>

  <%= f.label :looking_for %><br>
  <%= f.text_area :looking_for %><br>

  <%= f.label :image_path %><br>
  <%= f.text_field :img_url %><br>

  <%= f.submit %>
<% end %>

app/views/coders/show.html.erb
<%= link_to "Edit Coder Information", edit_coder_path(@coder) %><br>
<img src="<%= @coder.img_url %>" alt="Coder Image" height="150" width="150">

<h1><%= @coder.first_name %> <%= @coder.last_name %></h1>
<h4>About <%= @coder.first_name %></h4>
<%= @coder.about %><br>

<h4>What <%= @coder.first_name %> is looking for</h4>
<%= @coder.looking_for %><br>


<h4>Skills</h4>
<h5>Language / Skill Level</h5>
<% @skillsets.each do |skillset| %>
<%= skillset.language.name %> / <%= skillset.skill_level %>
<br>
<% end %>

app/views/languages/index.html.erb
<h1>ALL LANGUAGES</h1>

<% @languages.each do |language| %>
<h4><%= language.name %></h4>
<%= link_to "Delete Language", language_path(language), method: :delete %>
<% end  %>

app/views/languages/new.html.erb
<h1>Create a New Language</h1>

<%= form_for(@language) do |f| %>
  <%= f.label :language_name %><br>
  <%= f.text_field :name %><br>
  <br>

  <%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Want2Code</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Want2Code</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="/coders">Coders</a></li>
            <li><a href="/languages">Languages</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

  <% flash.each do |name, msg| %>
  <div class="alert alert-info" role="alert">
    <%= content_tag :div, msg, class: name %>
  </div>
  <% end %>
  <section class="pages">
    <%= yield %>
  </section>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/root/index.html.erb
ROOT VIEW
<br><br>

WELCOME TO THE WANT2CODE SITE! GREETING.
<br><br>

BASIC INFO ABOUT THE APP AND WHAT IT DOES.